/**
 * 3D Product Catalog Data with Interactive 3D Model Parameters,
 * Color Palettes, Available Sizes, Brand Classifications, and Related Products.
 */

export const CATEGORIES = [
  { id: 'all', name: 'All Products', icon: 'Sparkles' },
  { id: 'audio', name: 'Audio & Acoustics', icon: 'Headphones' },
  { id: 'wearables', name: 'Wearable Tech', icon: 'Watch' },
  { id: 'smartphones', name: 'Smartphones & Fold', icon: 'Smartphone' },
  { id: 'gaming', name: 'Gaming Gear', icon: 'Gamepad2' },
  { id: 'drones', name: 'Drones & Robotics', icon: 'Plane' },
  { id: 'optics', name: 'AR & Spatial Optics', icon: 'Glasses' },
];

export const BRANDS = [
  { id: 'all', name: 'All Brands' },
  { id: 'aura-labs', name: 'Aura Labs' },
  { id: 'apex-titanium', name: 'Apex Titanium' },
  { id: 'vortex-dynamics', name: 'Vortex Dynamics' },
  { id: 'mechstrike', name: 'MechStrike Pro' },
  { id: 'aerotech', name: 'AeroTech Robotics' },
  { id: 'viper-esports', name: 'Viper Esports' },
];

export const PRODUCTS = [
  {
    id: 'aura-pro-headphones',
    modelType: 'headphones',
    name: 'Aura Pro Spatial ANC Headphones',
    tagline: 'Lossless Hi-Res Audio with Dynamic Head Tracking',
    category: 'audio',
    brand: 'aura-labs',
    brandName: 'Aura Labs',
    price: 399,
    originalPrice: 479,
    rating: 4.9,
    reviewCount: 384,
    badge: 'Best Seller',
    badgeType: 'hot',
    inStock: true,
    stockCount: 18,
    releaseYear: 2026,
    sizes: ['Standard Fit', 'Pro Studio Edition', 'Memory Foam Max'],
    shortDesc: 'Precision-engineered with 40mm Beryllium acoustic drivers, active noise cancellation up to 48dB, and aircraft-grade aluminum headband.',
    description: 'The Aura Pro redefines wireless acoustic luxury. Featuring custom-tuned 40mm Beryllium acoustic transducers, the Aura Pro delivers deep, punchy sub-bass alongside crystalline high frequencies. Its quad-microphone beamforming array cancels unwanted ambient frequencies up to 48dB while maintaining pristine transparency when needed.',
    colors: [
      { id: 'cyber-cyan', name: 'Cyber Neon Cyan', hex: '#06b6d4', accentHex: '#0891b2', material: 'metallic', roughness: 0.25, metalness: 0.85 },
      { id: 'obsidian-black', name: 'Obsidian Matte', hex: '#18181b', accentHex: '#3f3f46', material: 'matte', roughness: 0.6, metalness: 0.3 },
      { id: 'royal-gold', name: 'Electrum Gold', hex: '#eab308', accentHex: '#ca8a04', material: 'metallic', roughness: 0.18, metalness: 0.95 },
      { id: 'alpine-silver', name: 'Lunar Silver', hex: '#e2e8f0', accentHex: '#94a3b8', material: 'glossy', roughness: 0.15, metalness: 0.9 },
      { id: 'emerald-pulse', name: 'Quantum Emerald', hex: '#10b981', accentHex: '#059669', material: 'metallic', roughness: 0.3, metalness: 0.75 },
    ],
    materials: [
      { id: 'anodized', name: 'Anodized Titanium', roughness: 0.25, metalness: 0.9 },
      { id: 'carbon', name: 'Forged Carbon Fiber', roughness: 0.45, metalness: 0.4 },
      { id: 'ceramic', name: 'Gloss Zirconia Ceramic', roughness: 0.1, metalness: 0.1 },
    ],
    features: [
      '40mm Diamond-like Carbon Beryllium Drivers',
      'Adaptive Hybrid Noise Cancellation (48dB reduction)',
      '65-Hour Battery Life with 10-Min Fast Turbo Charge',
      'Dual Lossless Bluetooth 5.4 + USB-C 24-bit/192kHz DAC',
      'Ultra-plush Memory Foam with breathable lambskin leather',
    ],
    specs: {
      'Acoustic Driver': '40mm Custom Beryllium Transducer',
      'Frequency Response': '5Hz – 48,000Hz Lossless',
      'Impedance': '32 Ohms @ 1kHz',
      'Battery Playtime': '65 Hours (ANC On)',
      'Weight': '264 grams',
      'Connectivity': 'Bluetooth 5.4 / LDAC / aptX Lossless / USB-C',
      'Microphones': '8-Mic Array with AI Wind Shielding',
    },
    explodedLayers: [
      { name: 'Outer Acoustic Shell', axis: 'x', distance: 1.8, desc: 'Aero-grade aluminum CNC milled backplate with micro-perforated acoustic vents.' },
      { name: '40mm Beryllium Driver Unit', axis: 'x', distance: 1.1, desc: 'High-flux neodymium magnet assembly producing studio-grade acoustic clarity.' },
      { name: 'ANC Sensor Array & DSP', axis: 'x', distance: 0.5, desc: 'Dual digital signal processors executing 192,000 noise calculation passes/sec.' },
      { name: 'Memory Foam Cushion', axis: 'x', distance: -0.8, desc: 'Ergonomic pressure-distributing memory foam encapsulated in protein leather.' },
      { name: 'Titanium Headband Core', axis: 'y', distance: 1.4, desc: 'Flexible shape-memory alloy core with calibrated clamping force.' },
    ],
    relatedProductIds: ['pulse-spatial-speaker', 'apex-chrono-smartwatch', 'nova-ar-smart-glasses'],
  },
  {
    id: 'apex-chrono-smartwatch',
    modelType: 'smartwatch',
    name: 'Apex Chrono Ultra Titanium',
    tagline: 'Aerospace Grade Titanium Case with Live Holographic Display',
    category: 'wearables',
    brand: 'apex-titanium',
    brandName: 'Apex Titanium',
    price: 649,
    originalPrice: 729,
    rating: 4.85,
    reviewCount: 290,
    badge: 'New Flagship',
    badgeType: 'new',
    inStock: true,
    stockCount: 12,
    releaseYear: 2026,
    sizes: ['41mm Slim', '45mm Standard', '49mm Ultra Summit'],
    shortDesc: 'Engineered for extreme summits and deep oceanic dives. 2000-nit sapphire crystal AMOLED display with ECG, dual-frequency GPS, and solar auxiliary glass.',
    description: 'Built like a hypercar for your wrist. The Apex Chrono Ultra combines grade 5 aerospace titanium, dual-band satellite positioning, and a military-grade sapphire crystal screen capable of hitting 2000 nits in direct sunlight. Includes live bio-telemetry, optical ECG sensors, and titanium link strap.',
    colors: [
      { id: 'titanium-natural', name: 'Raw Natural Titanium', hex: '#94a3b8', accentHex: '#64748b', material: 'metallic', roughness: 0.35, metalness: 0.9 },
      { id: 'cyber-orange', name: 'Apex Solar Orange', hex: '#f97316', accentHex: '#ea580c', material: 'metallic', roughness: 0.25, metalness: 0.8 },
      { id: 'stealth-black', name: 'Stealth DLC Carbon', hex: '#18181b', accentHex: '#27272a', material: 'matte', roughness: 0.5, metalness: 0.4 },
      { id: 'deep-azure', name: 'Abyssal Blue', hex: '#0284c7', accentHex: '#0369a1', material: 'metallic', roughness: 0.2, metalness: 0.85 },
    ],
    materials: [
      { id: 'grade5', name: 'Grade 5 Titanium Alloy', roughness: 0.3, metalness: 0.9 },
      { id: 'forged', name: 'Damascus Carbon Fiber', roughness: 0.4, metalness: 0.3 },
      { id: 'sapphire', name: 'Sapphire Crystal Bezel', roughness: 0.05, metalness: 0.1 },
    ],
    features: [
      'Sapphire Crystal 1.95" 2000-Nit AMOLED Display',
      '100M Water Resistance & High-Altitude Barometer',
      'Dual-Band Multi-Constellation GPS (L1 + L5)',
      '14-Day Battery Life on Single Charge / 60h Precision GPS',
      'Medical-grade ECG, SpO2 & Skin Temperature Sensors',
    ],
    specs: {
      'Chassis Material': 'Grade 5 Titanium CNC Beveled',
      'Display': '1.95" AMOLED, 480x480, 2000 nits peak',
      'Water Rating': '10 ATM / 100 Meters Diving Certified',
      'Battery Life': '14 Days Smartwatch / 45 Days Eco',
      'Sensors': 'ECG, Optical Heart, Pulse Ox, Altimeter, Gyro',
      'Strap Type': 'Quick-Release Fluoroelastomer & Titanium Link',
      'Weight': '58 grams (without strap)',
    },
    explodedLayers: [
      { name: 'Sapphire Crystal Glass', axis: 'z', distance: 1.5, desc: 'Ultra-scratch resistant 9 Mohs scale synthetic sapphire lens with anti-reflective coating.' },
      { name: 'OLED Active Dial Display', axis: 'z', distance: 0.9, desc: '1.95-inch ultra-vibrant circular AMOLED panel with 120Hz dynamic refresh rate.' },
      { name: 'Grade 5 Titanium Bezel & Housing', axis: 'z', distance: 0.3, desc: 'Corrosion-proof titanium main body with impact-resistant corner bumpers.' },
      { name: 'Processor & Dual-Band GPS Substrate', axis: 'z', distance: -0.6, desc: 'Quad-core energy-efficient neural engine and multi-satellite navigation antenna.' },
      { name: 'Ceramic Bio-Sensor Backplate', axis: 'z', distance: -1.3, desc: 'Hypoallergenic zirconia ceramic base featuring 8-LED photodiode optical sensor.' },
    ],
    relatedProductIds: ['aura-pro-headphones', 'vortex-cyberphone-pro', 'nova-ar-smart-glasses'],
  },
  {
    id: 'vortex-cyberphone-pro',
    modelType: 'smartphone',
    name: 'Vortex CyberPhone Fold Pro',
    tagline: 'Seamless Holographic Edge with Periscope Triple-Matrix Camera',
    category: 'smartphones',
    brand: 'vortex-dynamics',
    brandName: 'Vortex Dynamics',
    price: 1199,
    originalPrice: 1399,
    rating: 4.92,
    reviewCount: 512,
    badge: 'Tech Innovation',
    badgeType: 'special',
    inStock: true,
    stockCount: 9,
    releaseYear: 2026,
    sizes: ['256GB Storage', '512GB Storage', '1TB Ultra Edition'],
    shortDesc: 'A futuristic smartphone sculpted from forged titanium with an iridescent holographic display, 200MP periscope zoom, and zero-crease teardrop hinge.',
    description: 'Designed for the next decade of mobile computing. The Vortex CyberPhone Pro features an ultra-thin 4.8mm titanium unibody, a 6.8-inch Dynamic AMOLED 165Hz display, and a sapphire-covered periscope triple-camera system with mechanical optical zoom.',
    colors: [
      { id: 'iridescent-violet', name: 'Nebula Iridescent', hex: '#8b5cf6', accentHex: '#7c3aed', material: 'glossy', roughness: 0.12, metalness: 0.9 },
      { id: 'cyber-cyan', name: 'Matrix Cyan', hex: '#06b6d4', accentHex: '#0891b2', material: 'metallic', roughness: 0.2, metalness: 0.85 },
      { id: 'titanium-gold', name: 'Imperial Gold', hex: '#f59e0b', accentHex: '#d97706', material: 'metallic', roughness: 0.15, metalness: 0.95 },
      { id: 'matte-obsidian', name: 'Stealth Obsidian', hex: '#1e293b', accentHex: '#0f172a', material: 'matte', roughness: 0.5, metalness: 0.3 },
    ],
    materials: [
      { id: 'titanium', name: 'Polished Titanium Rail', roughness: 0.15, metalness: 0.9 },
      { id: 'frosted-glass', name: 'Nanotexture Frosted Glass', roughness: 0.4, metalness: 0.2 },
    ],
    features: [
      '6.8" 165Hz Dynamic AMOLED with 3200x1440 Resolution',
      '200MP Main + 50MP Ultra-Wide + 10x Periscope Telephoto',
      '3nm Hexa-Core Quantum AI Processor',
      '5500mAh Solid-State Battery with 120W HyperCharge (0-100% in 16 mins)',
      'IP69 Dust & High-Pressure Water Jet Protection',
    ],
    specs: {
      'Display': '6.8" 165Hz LTPO OLED, 3000 nits peak',
      'Processor': 'Quantum X-9 3nm Neural Octa-Core',
      'Camera System': '200MP Main (f/1.4 OIS) + 50MP UW + 10x Optical',
      'Storage': '512GB / 1TB UFS 4.1',
      'RAM': '16GB LPDDR5X Ultra',
      'Battery & Charging': '5,500mAh, 120W Wired, 50W Wireless Qi2',
      'Weight': '198 grams',
    },
    explodedLayers: [
      { name: 'Corning Gorilla Armor Glass', axis: 'z', distance: 1.6, desc: 'Ultra-durable anti-reflective front glass with 4x scratch resistance.' },
      { name: '165Hz Dynamic OLED Panel', axis: 'z', distance: 0.9, desc: 'Curved bezel-free organic light emitting diode screen.' },
      { name: 'Titanium Chassis & Vapor Chamber', axis: 'z', distance: 0.2, desc: '3D graphene liquid vapor cooling structure with aerospace titanium frame.' },
      { name: '200MP Triple Camera Module', axis: 'y', distance: 1.3, desc: 'Suspended periscope prism with 5-axis mechanical image stabilization.' },
      { name: 'Frosted Ceramic Back Plate', axis: 'z', distance: -1.2, desc: 'Matte AG frosted glass with inductive wireless charging coils.' },
    ],
    relatedProductIds: ['apex-chrono-smartwatch', 'aura-pro-headphones', 'nova-ar-smart-glasses'],
  },
  {
    id: 'mechstrike-artisan-keyboard',
    modelType: 'keyboard',
    name: 'MechStrike X Pro Keyboard',
    tagline: 'Gasket-Mounted Mechanical Keyboard with Per-Key RGB Wave',
    category: 'gaming',
    brand: 'mechstrike',
    brandName: 'MechStrike Pro',
    price: 249,
    originalPrice: 289,
    rating: 4.88,
    reviewCount: 420,
    badge: 'Popular',
    badgeType: 'hot',
    inStock: true,
    stockCount: 25,
    releaseYear: 2026,
    sizes: ['65% Compact', '75% Essential', 'TKL Tournament'],
    shortDesc: 'Custom 75% hot-swappable mechanical keyboard with CNC aluminum chassis, pre-lubed magnetic hall-effect switches, and acoustic gasket damping.',
    description: 'The ultimate typing and gaming weapon. Built with a solid CNC milled aluminum case, brass weight plate, double-shot PBT artisan keycaps, and customizable magnetic switches with 0.1mm adjustable actuation sensitivity.',
    colors: [
      { id: 'cyber-purple', name: 'Cyber Synthwave Purple', hex: '#a855f7', accentHex: '#9333ea', material: 'metallic', roughness: 0.25, metalness: 0.8 },
      { id: 'neon-cyan', name: 'Tokyo Neon Cyan', hex: '#06b6d4', accentHex: '#0284c7', material: 'metallic', roughness: 0.2, metalness: 0.85 },
      { id: 'stealth-grey', name: 'Gunmetal Titanium', hex: '#334155', accentHex: '#1e293b', material: 'matte', roughness: 0.45, metalness: 0.6 },
      { id: 'pure-white', name: 'Arctic Ice White', hex: '#f8fafc', accentHex: '#cbd5e1', material: 'glossy', roughness: 0.15, metalness: 0.2 },
    ],
    materials: [
      { id: 'aluminum', name: 'Anodized 6063 Aluminum', roughness: 0.2, metalness: 0.85 },
      { id: 'polycarbonate', name: 'Frosted Polycarbonate Plate', roughness: 0.3, metalness: 0.1 },
    ],
    features: [
      'Rapid Trigger Hall-Effect Magnetic Switches (0.1mm - 4.0mm adjustable)',
      'Acoustic 5-Layer Poron Gasket Isolation Mount',
      '8000Hz Polling Rate via 2.4GHz Wireless / Type-C',
      'Full RGB Underglow & Per-Key Programmable Matrix',
      'Custom CNC Brass Sound Weight Bar',
    ],
    specs: {
      'Layout': '75% Compact (84 Keys + Rotary Dial)',
      'Switch Type': 'Magnetic Hall Effect Rapid Trigger Pre-Lubed',
      'Case Material': 'CNC 6063 Anodized Aluminum',
      'Mounting Style': 'Gasket Mount with Poron Dampening',
      'Polling Rate': '8,000Hz Ultra-Low Latency (<0.125ms)',
      'Battery': '8,000mAh Dual-Cell (Up to 300h RGB off)',
      'Weight': '1.85 kg (Solid Brass Base)',
    },
    explodedLayers: [
      { name: 'Double-Shot PBT Keycaps', axis: 'y', distance: 1.8, desc: 'Textured oil-resistant keycaps with dye-sublimated futuristic legends.' },
      { name: 'Magnetic Switches Array', axis: 'y', distance: 1.1, desc: 'Factory hand-lubricated magnetic stem switches with dual-rail stabilization.' },
      { name: 'FR4 Aluminum Switch Plate', axis: 'y', distance: 0.6, desc: 'Flex-cut PCB plate with acoustic gasket tabs.' },
      { name: 'Multi-Layer Sound Dampening Poron', axis: 'y', distance: 0.2, desc: 'High-density memory foam eliminating ping and hollow resonance.' },
      { name: 'Solid CNC Aluminum Base Case', axis: 'y', distance: -1.0, desc: 'Heavyweight aluminum casing with integrated brass acoustic weight.' },
    ],
    relatedProductIds: ['viper-zero-mouse', 'aura-pro-headphones', 'vortex-cyberphone-pro'],
  },
  {
    id: 'aeroglide-hover-drone',
    modelType: 'drone',
    name: 'AeroGlide 4K Apex Drone',
    tagline: 'Ultralight Foldable Drone with 360° Omnidirectional Obstacle Avoidance',
    category: 'drones',
    brand: 'aerotech',
    brandName: 'AeroTech Robotics',
    price: 899,
    originalPrice: 999,
    rating: 4.95,
    reviewCount: 175,
    badge: 'Pro Tier',
    badgeType: 'special',
    inStock: true,
    stockCount: 7,
    releaseYear: 2026,
    sizes: ['Single Battery Pack', 'Fly More Creator Combo', 'Cinema Master Bundle'],
    shortDesc: 'Equipped with carbon fiber folding arms, spinning high-thrust rotors, 4K/120fps Hasselblad camera gimbal, and 45-minute flight endurance.',
    description: 'Designed for aerial filmmakers and tech enthusiasts. The AeroGlide 4K incorporates carbon fiber composite arms, omnidirectional LiDAR obstacle avoidance sensors, and a stabilized 3-axis mechanical gimbal camera.',
    colors: [
      { id: 'stealth-graphite', name: 'Stealth Graphite Grey', hex: '#334155', accentHex: '#0f172a', material: 'matte', roughness: 0.4, metalness: 0.5 },
      { id: 'racing-yellow', name: 'Mach Velocity Yellow', hex: '#eab308', accentHex: '#ca8a04', material: 'glossy', roughness: 0.2, metalness: 0.7 },
      { id: 'arctic-white', name: 'Alpine Polar White', hex: '#f1f5f9', accentHex: '#94a3b8', material: 'glossy', roughness: 0.18, metalness: 0.3 },
      { id: 'cyber-cyan', name: 'Quantum Cyan', hex: '#06b6d4', accentHex: '#0284c7', material: 'metallic', roughness: 0.25, metalness: 0.8 },
    ],
    materials: [
      { id: 'carbon-fiber', name: 'Carbon Fiber Weave', roughness: 0.35, metalness: 0.4 },
      { id: 'magnesium', name: 'Magnesium Aluminum Alloy', roughness: 0.2, metalness: 0.85 },
    ],
    features: [
      '4K 120fps HDR Video with 1-Inch CMOS Sensor',
      '45-Minute Maximum Flight Time per Smart Battery',
      '360° Omnidirectional Infrared & LiDAR Collision Shield',
      '15km Ultra-HD Video Transmission with OcuSync 4.0',
      'Automated Subject Tracking & AI Cinematic Flight Paths',
    ],
    specs: {
      'Camera': '1" CMOS 50MP, 4K/120fps, 10-bit D-Log M',
      'Gimbal': '3-Axis Mechanical Stabilization (Tilt, Roll, Pan)',
      'Max Speed': '72 km/h (Sport Mode)',
      'Flight Time': '45 Minutes per charge',
      'Transmission Range': '15 km (FCC compliant)',
      'Takeoff Weight': '249 grams (No FAA registration required)',
    },
    explodedLayers: [
      { name: 'Carbon Fiber Rotor Blades', axis: 'y', distance: 1.6, desc: 'Aerodynamically optimized low-noise composite propellers.' },
      { name: 'Brushless High-Torque Motors', axis: 'y', distance: 0.9, desc: 'Custom CNC wound high-efficiency brushless outrunners.' },
      { name: 'Aerodynamic Body Shell', axis: 'y', distance: 0.3, desc: 'Wind-tunnel tested aerodynamic frame minimizing air drag coefficient.' },
      { name: '4K Gimbal & LiDAR Sensor Suite', axis: 'y', distance: -0.9, desc: '3-axis stabilized motorized camera module and collision lasers.' },
      { name: 'Intelligent Flight Battery Core', axis: 'z', distance: -1.2, desc: 'High-energy density Lithium-Polymer smart battery pack.' },
    ],
    relatedProductIds: ['nova-ar-smart-glasses', 'vortex-cyberphone-pro', 'apex-chrono-smartwatch'],
  },
  {
    id: 'viper-zero-mouse',
    modelType: 'mouse',
    name: 'Viper Zero Wireless Mouse',
    tagline: 'Ultralight 38g Gaming Mouse with 36,000 DPI Optical Sensor',
    category: 'gaming',
    brand: 'viper-esports',
    brandName: 'Viper Esports',
    price: 159,
    originalPrice: 189,
    rating: 4.87,
    reviewCount: 310,
    badge: 'Esports Standard',
    badgeType: 'hot',
    inStock: true,
    stockCount: 34,
    releaseYear: 2026,
    sizes: ['Medium Ergonomic', 'Small Claw Grip', 'Large Palm Grip'],
    shortDesc: 'Featherlight 38-gram composite chassis with optical mechanical microswitches, pure PTFE glide feet, and 8000Hz polling rate.',
    description: 'Engineered for tournament champions where milliseconds decide victory. Featuring an ultra-lightweight skeletal composite chassis, zero-latency 8000Hz wireless polling, and optical switches rated for 100 million clicks.',
    colors: [
      { id: 'matte-black', name: 'Stealth Carbon Black', hex: '#18181b', accentHex: '#27272a', material: 'matte', roughness: 0.55, metalness: 0.2 },
      { id: 'ghost-white', name: 'Ghost Arctic White', hex: '#f8fafc', accentHex: '#e2e8f0', material: 'matte', roughness: 0.4, metalness: 0.1 },
      { id: 'cyber-cyan', name: 'Hyper Cyan', hex: '#06b6d4', accentHex: '#0891b2', material: 'metallic', roughness: 0.25, metalness: 0.8 },
      { id: 'toxic-green', name: 'Razer Lime Glow', hex: '#22c55e', accentHex: '#16a34a', material: 'metallic', roughness: 0.3, metalness: 0.7 },
    ],
    materials: [
      { id: 'magnesium', name: 'Magnesium Alloy Exoskeleton', roughness: 0.3, metalness: 0.8 },
      { id: 'carbon', name: 'Carbon Fiber Skeleton', roughness: 0.45, metalness: 0.3 },
    ],
    features: [
      '38g Ultra-Lightweight Engineered Exoskeleton',
      'Focus Pro 36,000 DPI Optical Sensor with 99.8% Resolution Accuracy',
      '8000Hz True Wireless Polling Rate (0.125ms Click Latency)',
      'Gen-3 Optical Mouse Switches (100M Clicks Lifespan)',
      '95 Hours Continuous Battery Life with Rapid USB-C Charging',
    ],
    specs: {
      'Sensor': 'Focus Pro 36K DPI Optical Engine',
      'Max Acceleration': '70G Acceleration / 750 IPS Speed',
      'Polling Rate': '8,000Hz Wireless / Wired',
      'Weight': '38 grams',
      'Switches': 'Optical Mechanical Microswitches Gen-3',
      'Feet': '100% Virgin Grade PTFE Glides',
      'Battery Life': '95 Hours continuous gaming',
    },
    explodedLayers: [
      { name: 'Honeycomb Shell Top', axis: 'y', distance: 1.5, desc: 'Ergonomic palm contour with precision ventilation cutouts.' },
      { name: 'Optical Microswitch Triggers', axis: 'y', distance: 0.8, desc: 'Zero debounce delay optical beam-breaker triggers.' },
      { name: 'PCB & 36,000 DPI Sensor', axis: 'y', distance: 0.1, desc: 'Ultra-miniaturized lightweight high-precision circuit board.' },
      { name: 'Low-Mass Lithium Cell', axis: 'z', distance: -0.6, desc: 'Centralized balanced mass micro-battery.' },
      { name: 'PTFE Glide Base Plate', axis: 'y', distance: -1.0, desc: 'Beveled zero-friction mouse skates for effortless flick shots.' },
    ],
    relatedProductIds: ['mechstrike-artisan-keyboard', 'aura-pro-headphones'],
  },
  {
    id: 'pulse-spatial-speaker',
    modelType: 'speaker',
    name: 'Pulse 360 Spatial Sound Sphere',
    tagline: 'Acoustic Cylinder with Dynamic Liquid Light Visualizer',
    category: 'audio',
    brand: 'aura-labs',
    brandName: 'Aura Labs',
    price: 329,
    originalPrice: 389,
    rating: 4.83,
    reviewCount: 195,
    badge: 'Design Award',
    badgeType: 'special',
    inStock: true,
    stockCount: 15,
    releaseYear: 2026,
    sizes: ['Compact Room Edition', 'Max Amphitheater Edition'],
    shortDesc: '360-degree room-filling acoustic cylinder wrapped in acoustic mesh fabric, dual passive subwoofers, and dynamic magnetic visualizer ring.',
    description: 'Transform any living space into a live amphitheater. The Pulse 360 features spatial acoustic array projection, twin opposed passive bass radiators, and an interactive LED illumination core that synchronizes with acoustic rhythms.',
    colors: [
      { id: 'midnight-black', name: 'Midnight Obsidian', hex: '#0f172a', accentHex: '#1e293b', material: 'matte', roughness: 0.6, metalness: 0.2 },
      { id: 'cyber-cyan', name: 'Electric Cyan Glow', hex: '#06b6d4', accentHex: '#0891b2', material: 'metallic', roughness: 0.2, metalness: 0.8 },
      { id: 'rose-gold', name: 'Sunset Rose Gold', hex: '#f43f5e', accentHex: '#e11d48', material: 'metallic', roughness: 0.15, metalness: 0.9 },
      { id: 'pearl-silver', name: 'Pearl Lunar White', hex: '#e2e8f0', accentHex: '#cbd5e1', material: 'glossy', roughness: 0.1, metalness: 0.4 },
    ],
    materials: [
      { id: 'fabric', name: 'Acoustic Woven Fabric', roughness: 0.7, metalness: 0.1 },
      { id: 'aluminum', name: 'Brushed Aluminum Top Ring', roughness: 0.2, metalness: 0.85 },
    ],
    features: [
      '360° Omnidirectional Spatial Acoustic Dispersion',
      'Dual Downward & Upward Firing Passive Radiators',
      'Real-Time Ambient LED Soundwave Pulse Visualizer',
      'Multi-Room Daisy Chain Pairing (Up to 100 Speakers)',
      '24-Hour Battery Life & Qi Wireless Reverse Charging Base',
    ],
    specs: {
      'Audio Output': '90W Peak Power Class-D Amplifiers',
      'Transducers': '3x 1.5" Full-Range Drivers + 1x 3.5" Subwoofer',
      'Frequency Range': '35Hz – 25,000Hz',
      'Battery Life': '24 Hours Playtime',
      'Connectivity': 'Wi-Fi 6, AirPlay 2, Spotify Connect, Bluetooth 5.4',
      'Waterproof': 'IPX7 Fully Submersible Rating',
      'Weight': '1.4 kg',
    },
    explodedLayers: [
      { name: 'Touch Control Aluminum Cap', axis: 'y', distance: 1.4, desc: 'Capacitive touch interface with gesture circular volume dial.' },
      { name: 'Acoustic LED Diffusion Ring', axis: 'y', distance: 0.8, desc: '360-degree dynamic multi-color reactive light ring.' },
      { name: '360° Array Mid-High Tweeters', axis: 'y', distance: 0.2, desc: 'Tri-directional angled neodymium sound transducers.' },
      { name: '3.5" Heavy Bass Subwoofer', axis: 'y', distance: -0.5, desc: 'Long-throw subwoofer with dual silicone suspensions.' },
      { name: 'Damped Weighted Silicone Base', axis: 'y', distance: -1.2, desc: 'Vibration absorbing base plate with QI charging receiver coils.' },
    ],
    relatedProductIds: ['aura-pro-headphones', 'vortex-cyberphone-pro'],
  },
  {
    id: 'nova-ar-smart-glasses',
    modelType: 'glasses',
    name: 'Nova AR Holographic Glasses',
    tagline: 'Ultra-Slim Micro-OLED AR Display with Spatial Audio',
    category: 'optics',
    brand: 'aura-labs',
    brandName: 'Aura Labs',
    price: 699,
    originalPrice: 799,
    rating: 4.91,
    reviewCount: 230,
    badge: 'Futuristic',
    badgeType: 'special',
    inStock: true,
    stockCount: 11,
    releaseYear: 2026,
    sizes: ['Standard Bridge (52-18)', 'Wide Bridge (56-20)'],
    shortDesc: 'Featherweight 64g titanium frames projecting a crisp 200-inch virtual screen with Micro-OLED waveguide optics and open-ear spatial sound.',
    description: 'The portal to spatial reality in a sleek designer form factor. The Nova AR glasses project a virtual 200-inch cinema display directly into your field of view using binocular Micro-OLED waveguide optics while weighing only 64 grams.',
    colors: [
      { id: 'titanium-black', name: 'Stealth Matte Titanium', hex: '#1e293b', accentHex: '#0f172a', material: 'matte', roughness: 0.4, metalness: 0.7 },
      { id: 'cyber-cyan', name: 'Cyber Neon Cyan', hex: '#06b6d4', accentHex: '#0891b2', material: 'metallic', roughness: 0.2, metalness: 0.9 },
      { id: 'champagne-gold', name: 'Champagne Titanium', hex: '#f59e0b', accentHex: '#d97706', material: 'metallic', roughness: 0.15, metalness: 0.95 },
      { id: 'silver-frost', name: 'Frost Platinum', hex: '#e2e8f0', accentHex: '#94a3b8', material: 'glossy', roughness: 0.1, metalness: 0.85 },
    ],
    materials: [
      { id: 'titanium-frame', name: 'Ultralight Titanium Beta Alloy', roughness: 0.2, metalness: 0.9 },
      { id: 'waveguide', name: 'Optical Micro-Waveguide Glass', roughness: 0.05, metalness: 0.05 },
    ],
    features: [
      'Dual Micro-OLED Waveguide Optics (1080p Per Eye / 50° FOV)',
      'Simulates a 200-inch Virtual Theater at 4 Meters Distance',
      'Ultra-Lightweight 64g Everyday Wearable Chassis',
      'Directional Spatial Open-Ear Acoustic Micro-Speakers',
      'Universal USB-C DisplayPort Compatibility (iPhone, Mac, PC, SteamDeck)',
    ],
    specs: {
      'Optics': 'Sony Micro-OLED Optical Waveguide Engine',
      'Resolution': '1920 x 1080 per eye (49 PPD)',
      'Brightness': 'Up to 1,800 nits with electrochromic dimming',
      'Weight': '64 grams',
      'Audio': 'Dual Directional Acoustic Speakers + Dual Noise-Cancelling Mics',
      'Sensors': '6-DoF Head Tracking, Gyro, Proximity Sensor',
      'Cable': 'Magnetic Detachable Ultra-Soft USB-C Cable',
    },
    explodedLayers: [
      { name: 'Electrochromic Smart Tint Lenses', axis: 'z', distance: 1.5, desc: 'Variable opacity glass transitioning from 100% clear to dark sunglasses tint.' },
      { name: 'Micro-OLED Optical Waveguides', axis: 'z', distance: 0.8, desc: 'Diffractive optical waveguides redirecting high-density photon beams.' },
      { name: 'Titanium Eyewear Frame Bridge', axis: 'z', distance: 0.1, desc: 'Flexible shape-retaining beta titanium structural chassis.' },
      { name: 'Spatial Audio Temple Nodes', axis: 'x', distance: 1.2, desc: 'Directional acoustic chambers channeling private audio directly into ears.' },
      { name: 'Silicone Air-Cushion Nose Pads', axis: 'y', distance: -0.8, desc: 'Adjustable titanium-core hypoallergenic memory nose pads.' },
    ],
    relatedProductIds: ['apex-chrono-smartwatch', 'vortex-cyberphone-pro', 'aura-pro-headphones'],
  },
];

export const PROMO_CODES = {
  'AURA20': { discountPercent: 20, description: '20% Off Storewide' },
  'CYBER3D': { discountPercent: 15, description: '15% Off 3D Showcase Launch' },
  'VIP50': { discountAmount: 50, description: '$50 Off Orders over $300' },
};
